#!/usr/bin/env python3
"""Source of truth for data/funding.json (site owner). Run: python3 scripts/gen_funding.py && node scripts/rank.js"""
import json, os
V="2026-10-01"
def it(id,name,cat,gives,elig,needs,deadline,dstatus,effort,value,fit,url,verified,notes):
    return dict(id=id,name=name,category=cat,gives=gives,eligibility=elig,intima_needs=needs,deadline=deadline,deadline_status=dstatus,effort=effort,value=value,fit=fit,rank_score=0,url=url,verified_on=V,verified=verified,notes=notes)
SP="Source page opened and read on verified_on date."
SN="Seen only in a search snippet of the official/secondary source; page not opened - re-check before acting."
items=[
it("dpiit","DPIIT Startup recognition (Startup India)","govt","Recognition unlocks: self-certification (labour/environment), 80% rebate on patent filing + free facilitator fees, 80-IAC income-tax holiday (3 of first 10 yrs; Pvt Ltd/LLP incorporated after 1 Apr 2016), GeM/EMD exemptions, and is the gateway to SISFS and many incubator calls.","Pvt Ltd / registered partnership / LLP; <=10 yrs from incorporation; turnover <= Rs 200 cr; not formed by splitting an existing business; innovative/scalable.","Confirm Intima's legal entity (if still a proprietorship, incorporate as Pvt Ltd/LLP first); certificate of incorporation, short product description, website (intimacare.in).","rolling","rolling",2,4,5,"https://www.startupindia.gov.in/content/sih/en/startup-scheme.html",True,"Prerequisite for most Indian govt/incubator money. "+SP+" (The dedicated recognition URL returned 404 on the check date - apply via startupindia.gov.in.)"),
it("nerve","NERVE CoE Nagpur (STPI x MeitY x Govt of Maharashtra)","incubator","Incubation space at STPI Nagpur (Parsodi), GPU/AI infra, mentoring, IP/legal support, investor connect and seed-fund support of up to Rs 50 lakh; healthcare is a named focus (AIIMS Nagpur, GMC, IGGMC partners).","Startups/innovators in AI-led solutions for healthcare, agri, environment, mining, other. Cohort-based Open Challenge Program via Sayuj portal.","DPIIT recognition (likely expected), MVP/product demo, pitch deck, clear AI/health-informatics angle (AI wellness companion, risk screens).","next cohort date not announced","unverified",3,4,5,"https://nerve.stpi.in/",True,"Local (Nagpur) + healthcare + AI = best structural fit. Search results indicate OCP Cohort 1 closed 15 Jul 2026 and no new call is listed; watch nerve.stpi.in and Sayuj. "+SP),
it("stpi-ocp7","STPI MedTech CoE Open Challenge Program 7.0 (NIRMAAN)","challenge","Seed funding of up to Rs 50 lakh (pitch to MedTech CoE Investment Committee after onboarding), labs, mentoring, IPR/CDSCO guidance, investor access. No application fee.","Indian startup (Pvt Ltd / partnership / LLP, <=10 yrs, turnover <= Rs 100 cr, >=51% Indian ownership) in Medical Electronics & Health Informatics; unregistered founders may apply but must incorporate within 3 months of selection.","Registered entity or plan to incorporate; Sayuj portal login; pitch deck; MVP/prototype description. Note: selected startups pay 1-3% incubation equity OR per-seat fee; support is based at SGPGIMS Lucknow (virtual support possible).","2026-10-08","verified",3,4,3,"https://medtech.stpi.in/open-challenge/open-challenge-7",True,"Only dated opportunity within 30 days. Intima is a consumer wellness app, not a medical device - 'Health Informatics' is the angle; fit is moderate, not strong. Screening starts 9 Oct 2026. "+SP),
it("infed","IIM Nagpur - InFED (AIC-InFED, SISFS partner incubator)","incubator","Incubation + mentoring from IIM Nagpur; historically a SISFS-disbursing incubator (up to Rs 20L grant / Rs 50L convertible/debt via the scheme).","DPIIT-recognised startup; healthcare/biotech/AI/IoT among focus sectors.","DPIIT certificate, incorporation docs, founder KYC, pitch deck, prototype/validation notes.","rolling","unverified",3,3,4,"https://www.iimnagpur.ac.in/infed",True,"InFED existence/role confirmed on the official IIM Nagpur page. Programme/SISFS specifics come from a third-party guide (raiseonic.com) - confirm directly (infed@iimnagpur.ac.in). Rolling incubation enquiries are normally possible."),
it("sisfs","Startup India Seed Fund Scheme (SISFS)","govt","Up to Rs 20 lakh grant (PoC/prototype/trials, milestone-based) and up to Rs 50 lakh via convertible debentures/debt-linked instruments (<= repo rate, <=5 yrs), disbursed through selected incubators.","DPIIT-recognised, incorporated not more than 2 years ago at time of application; no individual applicants.","DPIIT recognition; entity < 2 yrs old; incubator preference (up to 3).","closed (31 May 2026)","closed",3,3,4,"https://seedfund.startupindia.gov.in/faq",True,"Per official portal notice relayed by multiple sources, startup applications closed 31 May 2026 and no successor window has been announced. FAQ page (read today) confirms terms. Re-check portal monthly. Intima must also be <2 yrs incorporated."),
it("big","BIRAC BIG - Biotechnology Ignition Grant","govt","Up to Rs 50 lakh grant-in-aid for 18 months to reach proof of concept, via BIG partner incubators.","Biotech-linked innovation/startups; applies through BIRAC online portal during open calls.","A biotech/health-tech PoC with commercialisation potential; digital wellness software is a stretch for BIRAC's biotech remit - would need a clinical/validation angle.","none open (no 26th call published)","unverified",5,5,2,"https://birac.nic.in/big.php",True,"Official page: calls are announced 1 Jan and 1 Jul, open ~45 days. BIRAC's call list shows the 25th call closed 30 Nov 2025 and no 26th call yet. A third-party site claims 15 Aug 2026 - NOT supported by BIRAC; ignored. "+SP),
it("prayas","DST NIDHI-PRAYAS 2.0","govt","Prototype grant up to Rs 20L (PRAYAS Centre) or Rs 40L (Advanced centre), 15 months, fab-lab access.","Hardware/physical prototype focus; startups <=5 yrs, turnover <= Rs 1 cr, >=51% Indian equity.","Not eligible as-is: guidelines explicitly exclude pure software, e-commerce, service and app-based solutions.","periodic calls by individual centres","unverified",4,3,1,"https://nidhi-prayas.org/innovators/",True,"Listed for completeness; only relevant if Intima ships its own wearable/hardware (wearables are built but off). "+SP),
it("nidhi-eir","DST NIDHI-EIR (Entrepreneur-in-Residence)","govt","Monthly subsistence grant (Rs 10,000-30,000/month, up to Rs 3.6 lakh total) for 12-18 months at a host incubator (TBI).","Aspiring/budding entrepreneur with a technology business idea; apply to a chosen host incubator (eligibility list in DST FAQ).","Pitch + plan; choose host TBI from current calls list; cannot run in parallel with PRAYAS.","per-incubator calls","unverified",2,2,3,"https://www.nidhi-eir.in/currentcalls.php",False,"Calls are posted per incubator (e.g. STEP Pune); check which are open. Amounts from DST ISTI FAQ search snippet. "+SN),
it("samridh","MeitY SAMRIDH (accelerator-led matching)","govt","Accelerator gets Rs 2 lakh per startup; startups can get matching funding up to Rs 40 lakh; health-tech is a named vertical.","Apply via MeitY-selected accelerators (43 accelerators in 16 states). NB: SAMRIDH *Impact* (samridhimpact.com) is a different programme requiring >= Rs 3 cr revenue and 2 yrs - not Intima.","DPIIT recognition, MVP, traction metrics, accelerator selection; matching investor is the hard part.","per-accelerator","unverified",4,4,3,"https://msh.meity.gov.in/samridh/acceleratorlist",False,"PIB release (via search) confirms Rs 2L / Rs 40L structure. No open call verified. "+SN),
it("tide2","MeitY TIDE 2.0 incubation centres","govt","Seed/incubation support through TIDE 2.0 centres for ICT startups in healthcare and other priority areas.","Per-centre calls (example: IIMCIP 2025 cohort ran 24 Jul-25 Aug 2025).","DPIIT recognition, tech-enabled healthcare MVP.","none open found","unverified",3,3,3,"https://msh.meity.gov.in/schemes/tide",False,"No Nagpur-specific TIDE call verified. "+SN),
it("genesis","MeitY GENESIS EIR 3.0","govt","Up to Rs 10 lakh financial assistance + incubation via GENESIS incubators.","Aspiring entrepreneurs/early-stage founders in electronics/IT/ICT/DeepTech.","Idea/MVP, online application.","2026-09-03","closed",3,3,3,"https://www.pib.gov.in/PressReleasePage.aspx?PRID=2302611",False,"Cohort 3 window 4 Aug-3 Sep 2026 has closed; watch for Cohort 4. "+SN),
it("msins","Maharashtra State Innovation Society (MSInS) / Maharashtra Startup Policy 2025","govt","State startup-policy benefits and programmes (e.g. roadshows, Startup Yatra, state-level grants/support).","Maharashtra-based startups; details per scheme.","DPIIT recognition + Maharashtra registration; Udyam/other state registrations as required.","none open found","unverified",3,3,3,"https://msins.in/StartupYatra",False,"msins.in page did not render for our fetch; search shows the last Startup Yatra was 2022 and 2026 activity is a Maharashtra Roadshow (concluded Apr 2026). Do not assume any grant scheme is open. "+SN),
it("civn","VNIT Nagpur - Centre for Innovation (CIVN) / V3F incubator","incubator","Low-cost incubation space, mentors, M.Tech student support, networking; V3F reported as VNIT's new tech incubator.","Technology-based ventures; proposals screened by an advisory panel.","Business plan, tech angle; academic tie-up helps.","rolling","unverified",2,2,3,"https://vnit.ac.in/centre-for-innovation/",True,"CIVN page read (small incubator, 5 units, Section 8 company). V3F details only from LinkedIn/aggregator - unverified."),
it("aic-thub","AIC T-Hub Healthcare Programme (Cohort 6)","accelerator","Zero-equity accelerator with mentors, investors and healthcare ecosystem access.","Should have MVP validated, in commercialisation and have received Rs 50 lakh funding or equivalent revenue.","Not eligible yet (pre-revenue, unfunded).","2026-08-10","closed",3,3,1,"https://www.t-hub.co/healthcare",True,"Applications launched 7 Jul and closed ~10 Aug 2026. Revisit once there is revenue/funding. "+SP),
it("pierc","PIERC HealthTech Accelerator (Parul University)","accelerator","6-month hybrid programme: clinical validation inside a 1,100-bed hospital, doctor mentorship, investor readiness, demo day; 10 startups.","MVP + prototype + early customers + pilot-ready; Pvt Ltd (or register within 2 months) with DPIIT.","Entity, MVP, early-customer evidence, ability to attend in-person residencies in Vadodara.","not stated on page","unverified",3,2,2,"https://www.pierc.org/healthtech-accelerator",True,"Page lists conflicting dates (applications open 13 Aug / 1 Sep; start 18 Sep / 9 Oct 2026) and no closing date - treat as likely closed or closing; confirm by email before investing time. "+SP),
it("yc","Y Combinator - Winter 2027","accelerator","Standard YC investment on acceptance; 3-month batch in San Francisco; $12M+ in partner credits (OpenAI, Anthropic, AWS, Google Cloud, Azure, Stripe...).","Any stage incl. pre-revenue; strong founding team, big market; in-person batch.","Founder application (and ideally a 1-min video), crisp traction/insight story; relocation or travel for batch.","2026-11-02","verified",4,5,2,"https://www.ycombinator.com/apply/",True,"On-time deadline 2 Nov 2026 8pm PT (decision by 11 Dec). 32 days away - outside the 30-day draft window. Pre-revenue consumer health from India is a long shot; apply only if the founder wants the US path. "+SP),
it("surge","Surge by Peak XV","accelerator","Equity seed investment from $500K up to $5M plus operator support; next cohort kicked off Sep 2026.","Open year-round, rolling; founder strength, market size, early customer love if launched. Any sector.","Retention/engagement evidence is what they look for - exactly what the Pulse tracker + doctor-referral pilots can supply.","rolling","rolling",3,5,2,"https://surge.peakxv.com/faqs",True,SP),
it("antler","Antler India (AI Residency / direct)","accelerator","Standard deal up to ~INR 4 Cr for ~11% equity; 3-week residency decision; AI perks.","Pre-launch/pre-revenue welcome but focus is AI-first startups; full-time commitment in Bengaluru.","Frame Intima as AI-companion-led; co-founder/full-time team.","next residency 'announced soon'","unverified",3,4,2,"https://www.antler.co/location/india",True,"2nd AI Residency deadline (19 Feb 2026) passed; India page says next one TBA and invites direct contact. "+SP),
it("eir-accelerator","Eir Growth Programme (women's health accelerator, Europe)","accelerator","6-month accelerator for women's-health startups.","Women's-health focused; European orientation.","Intima is also a men's platform; Europe market story needed.","next call summer 2027 (per search)","unverified",3,2,2,"https://eir-accelerator.com/programme",False,"Search says applications are closed and next call is summer 2027. Other global femtech calls found (W Accelerate closed 2 Sep 2026; Women's Health Europe Forum pitch, EU/UK only, 8 Oct) are not accessible to Intima. "+SN),
it("rainmatter","Rainmatter (Zerodha) - health & wellness investor","vc","Backed Allo Health (led Rs 16 cr pre-Series A), Bold Care (led $5M Series A, Feb 2025) and reportedly Gytree; fits India consumer health with a privacy/ethos angle.","Cold intro/pitch; investor looks at India wellness/health founders.","Short deck with retention data, clear privacy position, unit-economics hypothesis; do not over-claim privacy.","rolling","rolling",3,4,4,"https://entrackr.com/snippets/allo-health-raises-rs-16-cr-in-pre-series-a-round-8846048",False,"Typical cheque for first round not published; lead cheques seen: Rs 16 cr (Allo pre-A), $5M (Bold Care A). Sources: Entrackr; Economic Times (Bold Care): https://economictimes.indiatimes.com/tech/funding/wellness-co-bold-care-raises-5-million/articleshow/118125302.cms . Press reports - "+SN),
it("nexus","Nexus Venture Partners","vc","Backed Allo Health (seed ~$4.4M round with angels incl. Binny Bansal, Deepinder Goyal) and participated in Proactive For Her.","Warm intro; usually seed+ with traction.","Revenue/retention proof first; too early for cold approach.","rolling","rolling",4,4,2,"https://www.digitalhealthnews.com/healthtech-startup-allo-health-raises-inr-16-cr-in-pre-series-a-round-eyes-expansion",False,"Cheque ~ seed round of ~$4.4M (shared with angels) - press reports. "+SN),
it("vertex","Vertex Ventures SEA & India","vc","Led Proactive For Her $5.5M Series A (Feb 2022); Proactive For Her was later acquired by IVF Access (Jun 2025, terms undisclosed).","Series-A stage in this example.","Traction far beyond pre-revenue.","rolling","rolling",5,4,1,"https://www.vertexventures.sg/news/proactive-for-her-a-women-s-healthtech-startup-raises-5-5-million-in-series-a-round-led-by-vertex-ventures/",False,"Useful as a comparable/exit signal rather than a near-term target. "+SN),
it("sauce","Sauce.vc / Rainforest Ventures (early consumer-wellness)","vc","Backed Misters (men's health) with Rs 3.5 crore (as reported).","Early-stage consumer wellness.","Brand/traction story; small-cheque seed.","rolling","rolling",3,2,3,"https://smestreet.in/infocus/misters-in-raises-inr-3-5-crore-as-series-b-funding-led-by-sauce-vc-rainforest-ventures/",False,"Cheque ~Rs 3.5 cr per press; round labelled 'Series B' by the outlet - treat label with caution. Maya's funding history (Prime Venture Partners, Rajan Anandan) is from older press, not verified. "+SN),
it("aws","AWS Activate - Founders (self-funded)","credits","Start with $1,000 in credits; selected participants up to $5,000. (Portfolio tier up to $200K needs an Activate Provider Org ID, e.g. accelerator/VC.)","Pre-Series B, founded in last 10 years, AWS account on paid plan, new to Activate.","AWS Builder ID, AWS account, company details; decision in 5-10 business days.","rolling","rolling",1,2,4,"https://aws.amazon.com/startups/credits",True,"Only useful if Intima runs (or will move) infra on AWS. "+SP),
it("google","Google for Startups Cloud Program","credits","$2,000 for pre-funded MVP stage; $200K-$350K once institutionally funded/early stage.","Pre-funded tier: working MVP, clear model, company site + domain email, incorporated recently, Cloud billing account (details from search snippet).","Cloud billing ID, company-domain email.","rolling","rolling",1,1,3,"https://cloud.google.com/startup",True,"Headline amounts read on official page; fine print from a snippet - confirm. Relevant if the AI provider/infra is Google (Gemini/Vertex)."),
it("microsoft","Microsoft for Startups (Founders Hub)","credits","Up to $150,000 in Azure credits plus AI tools and GitHub/dev benefits.","Tiered; details not shown on fetched page.","Company profile; Azure usage plan.","rolling","rolling",2,3,3,"https://www.microsoft.com/en-us/startups",True,"Headline 'up to $150,000' read on official page; eligibility tiers and India specifics unverified."),
it("vercel","Vercel for Startups","credits","Up to $30,000 Flexible Commitment Amount, Enterprise-tier access.","Eligible teams (program form); criteria not on page.","Only if frontend is on Vercel.","rolling","rolling",2,2,2,"https://vercel.com/startups",True,"Headline read on official page; eligibility not stated. "+SP),
it("supabase","Supabase startup perks","credits","Reported: free Team plan months / ~$300 credits via direct form or partner programs (AWS Activate, YC, Vercel).","Early-stage; often <$5M funding; some offers restricted to VC-backed.","Only if backend is on Supabase.","rolling","rolling",1,1,2,"https://supabase.com/solutions/startups",False,"Official page (supabase.com/open-source/startups) returned 404; figures from third-party directories. "+SN),
it("claude","Anthropic - Claude for Startups","credits","API credits + priority rate limits.","Official FAQ: need equity funding from an institutional investor, founded within 4 years, no prior Anthropic credits (page also says open to those without VC backing - ambiguous). Credits work on first-party Claude API only.","Currently unfunded => likely not eligible; also only relevant if Intima's AI companion uses Claude.","rolling","rolling",1,3,1,"https://claude.com/programs/startups",True,"Do not assume the AI provider; check the stack first. OpenAI's program is VC-referral-only per a third-party summary (unverified). "+SP),
it("pieds","PIEDS (BITS Pilani) Womenpreneur for Bharat 4.0","challenge","Up to Rs 15 lakh funding + incubation, for women-led startups from Tier 2/3 cities.","Women hold >51% equity, DPIIT, revenue < Rs 1 cr, PoC/prototype.","Not met unless equity structure qualifies; closed anyway.","2026-09-23","closed",3,3,1,"https://startupgrantshub.com/opportunities/pieds-womenpreneur-for-bharat-4-0/",False,"Deadline extended to 23 Sep 2026 (via LinkedIn/aggregators) and has passed. "+SN),
it("swasthya","SwasthyaTech Synapse 2026 (IHFC IIT Delhi + AIIMS)","challenge","Up to Rs 2 cr individual / Rs 5 cr consortium for healthcare technology prototypes TRL4+.","Academia/hospitals/healthtech; focus on devices, robotics, diagnostics.","Not a software wellness fit.","2026-09-30","closed",4,4,1,"https://www.linkedin.com/posts/seed-grant-studio_swasthyatech-synapse-2026-funding-up-activity-7508005313690779648-mD44",False,"Closed 30 Sep 2026. Shows the type of device-centric calls that need the (currently off) wearables. "+SN),
]
core=[("Problem","Millions of Indians avoid care for periods, PCOS/PCOD, fertility, sexual health and low energy because of stigma, judgement and fear that sensitive health data will be exposed or sold. Existing apps either require accounts and phone numbers, or push products rather than guiding people to credible care."),
("Solution","Intima Health (intimacare.in) is a no-login health platform for women and men. Users get an anonymous ID with a PIN and an 8-character backup code - no phone number, email or name. Women: cycle, ovulation and fertility tracking, BBT, IVF and pregnancy modes, hormonal dashboard. Men: energy/stress/vitality tracking, ED score, low-T screen, testosterone rhythm, performance log, lab results, Kegel. An AI wellness companion (30 messages/day), 7-day programs, Partner Mode, and care access: doctor map, anonymous booking, chat/video consults."),
("Traction (honest)","Pre-revenue. [Founder to add verified numbers: live users, doctor partners, pilot/referral counts, day-7/day-30 retention. Do not include figures that cannot be evidenced.] We run a daily synthetic-persona quality tracker (Intima Pulse) that logs issues, performance and AI-companion quality."),
("Privacy stance (honest)","Intima does not require identity to use the product: no login, no phone/email. It is NOT an on-device-only product: health logs sync to our cloud, AI chat messages are processed by a third-party AI provider, and consult messages are encrypted at rest with an operator-held key (not end-to-end encrypted). We make no claim beyond that."),
("Ask","[Founder to fill: amount, instrument, and use of funds - e.g. 6-12 months of runway to (1) lift day-30 retention of doctor-referred users, (2) validate the AI companion safety/language quality (Hindi/Hinglish), (3) run a clinician-referral pilot.]")]
ocp=[("Problem","Sensitive reproductive and sexual health is under-served in India: people delay care due to stigma and distrust of how health data is handled. Doctors also lack continuous patient-reported data between visits (cycles, symptoms, energy, lab values)."),
("Solution (health informatics angle)","Intima Health is an anonymous, no-login patient-reported-outcomes and guidance platform: structured logging (cycle/ovulation/BBT/IVF/pregnancy for women; energy, stress, ED score, low-T screen and lab results for men), an AI wellness companion with safety guardrails, 7-day programs, Partner Mode and a doctor-referral/consult layer (doctor map, anonymous booking, chat/video). Data is structured so a clinician can review trends."),
("Stage and traction (honest)","Live product at intimacare.in; pre-revenue. [Founder to add: users, referrals, retention.] Continuous automated persona testing (Meera, 28, PCOS/TTC; Arjun, 34, stress/low energy) tracks bugs, load time and AI-companion safety."),
("Privacy and safety (honest)","No login/phone/email required. Not on-device-only: logs sync to cloud; AI chat goes to a third-party AI provider; consult messages are encrypted at rest with an operator-held key (not end-to-end). The AI companion is wellness guidance, not diagnosis; it should defer to clinicians for medical decisions. We are not claiming CDSCO clearance."),
("Why STPI MedTech CoE","Health-informatics focus; access to clinical mentors for validation of our screens and safety design; IPR/regulatory guidance on where wellness ends and software-as-medical-device begins; clinical partners for a doctor-referred cohort. We understand incubation equity of 1-3% (or a per-seat fee) applies, and support is based in Lucknow with virtual options."),
("Ask","Selection into OCP 7.0 and the opportunity to pitch to the MedTech CoE Investment Committee for seed funding (up to Rs 50 lakh), to fund a clinician-validated referral pilot and retention improvements. [Founder to confirm entity type/incorporation before submitting; Sayuj portal login needed.]")]
drafts=[dict(id="d-ocp7",for_item="stpi-ocp7",title="STPI MedTech OCP 7.0 (deadline 8 Oct 2026) - application text DRAFT (not submitted)",blocks=[dict(label=l,text=t) for l,t in ocp]),
dict(id="d-core",for_item="dpiit",title="Reusable core pitch (for SISFS-type, incubator, NERVE, accelerator forms) - DRAFT",blocks=[dict(label=l,text=t) for l,t in core])]
out=dict(updated="2026-10-01T10:30:00+05:30",today="2026-10-01",items=items,drafts=drafts)
p=os.path.join(os.path.dirname(__file__),"..","data","funding.json")
json.dump(out,open(p,"w"),indent=1,ensure_ascii=False); open(p,"a").write("\n"); print(len(items),"items")
